1704827012.527067:
    QFontDatabase(a0: QFontDatabase): not enough arguments on line 1016 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in FontFaceListWidget.__init__
1704827119.4041479:
    QFontDatabase(a0: QFontDatabase): not enough arguments on line 1016 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in FontFaceListWidget.__init__
1704827349.043562:
    type object 'Qt' has no attribute 'IgnoreAspectRatio' on line 520 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.populate_video_list
1704900073.0941231:
    'global_song_background' on line 543 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1704900176.8995836:
    type object 'Qt' has no attribute 'MatchExactly' on line 663 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1704900259.7341437:
    wrapped C/C++ object of type QWidget has been deleted on line 669 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1704900288.200264:
    wrapped C/C++ object of type QWidget has been deleted on line 669 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1704929306.8644383:
    'FontFaceComboBox' object has no attribute 'item' on line 244 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1704929701.1882846:
    'FontFaceComboBox' object has no attribute 'item' on line 586 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705009054.8039887:
    'shadow_color' on line 233 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1705083259.0845912:
    [WinError 3] The system cannot find the path specified: 'C:\\Users\\pasto\\Nextcloud\\Documents\\Python Workspace\\project_on../data' on line 891 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in CheckFiles.run
1705083425.3776731:
    [WinError 3] The system cannot find the path specified: 'C:\\Users\\pasto\\Nextcloud\\Documents\\Python Workspace\\project_on../data' on line 895 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in CheckFiles.run
1705083441.672611:
    [WinError 3] The system cannot find the path specified: 'C:\\Users\\pasto\\Nextcloud\\Documents\\Python Workspace\\project_on../data' on line 895 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in CheckFiles.run
1705083465.5807881:
    [WinError 3] The system cannot find the path specified: 'C:\\Users\\pasto\\Nextcloud\\Documents\\Python Workspace\\project_on../data' on line 895 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in CheckFiles.run
1705263680.1057587:
    GUI.live_from_remote_signal[str] signal has 1 argument(s) but 0 provided on line 44 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\web_remote.py in RemoteServer.remote
1705263751.8707945:
    GUI.live_from_remote_signal[str] signal has 1 argument(s) but 0 provided on line 45 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\web_remote.py in RemoteServer.remote
2024-01-16 22:32:33.802226:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:41.603431:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:42.500339:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:43.098687:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:43.625262:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:44.107551:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:44.726925:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:45.452962:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:45.650499:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:45.828348:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:46.009033:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:46.176677:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:46.358930:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:46.522718:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:46.702041:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:46.880853:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:47.053814:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:47.231343:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:47.393914:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:47.575161:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:47.745850:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:47.917308:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:48.083080:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:48.267383:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:48.440426:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:48.611562:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:48.792727:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:48.959235:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:49.117407:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:49.305576:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:49.476784:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:49.658780:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:49.830501:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:49.991153:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:50.168178:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:50.352483:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:50.514491:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:50.691486:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:50.855954:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:51.045586:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:51.223538:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:51.403955:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:51.574948:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:51.751652:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:51.919274:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:52.102620:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:52.275392:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:52.451758:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:52.625765:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:52.810985:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:52.988285:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:53.168067:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:53.347935:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:53.523443:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:53.698531:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:53.869589:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:54.043921:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:54.225566:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:54.396742:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:54.586649:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:54.772004:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:54.947896:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:55.116669:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:55.309797:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:55.491325:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:55.674121:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:55.850705:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:32:56.019856:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:01.795777:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:01.973388:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:02.161277:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:02.334488:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:02.525386:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:02.705039:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:02.879549:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:03.047920:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:03.228934:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:03.415398:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:03.582360:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:03.750982:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:03.925101:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:04.095776:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:04.267666:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:04.452895:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:04.620169:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:04.827764:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:05.013160:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:05.171144:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:05.358813:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:05.533282:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:05.705352:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:05.897697:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:06.095053:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:06.283894:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:06.530888:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:06.703061:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:06.880148:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:07.060307:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:07.268495:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:07.449397:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:07.641308:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:07.823301:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:08.012768:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:08.192594:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:08.375750:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:08.579862:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:08.770421:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:08.946481:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:09.122874:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:21.357608:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:21.538145:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:21.731920:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:21.919931:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:22.084799:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:22.276976:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:22.448049:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:22.629017:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:22.786858:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:22.954869:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:23.127666:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:23.315237:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:23.514397:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:23.641448:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:23.829784:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:23.995354:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:24.163360:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:24.320473:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:24.482567:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:24.658631:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label2024-01-16 22:33:24.820250:
    UNHANDLED EXCEPTION
    'RuntimeError'
    wrapped C/C++ object of type QLabel has been deleted
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py, line 156 in update_status_label1705850997.8485947:
    argument of type 'NoneType' is not iterable on line 566 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705851066.2736924:
    argument of type 'NoneType' is not iterable on line 567 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705851099.6620746:
    argument of type 'NoneType' is not iterable on line 568 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705851139.8892887:
    argument of type 'NoneType' is not iterable on line 596 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705941972.5897365:
    can only concatenate str (not "NoneType") to str on line 579 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705942016.232211:
    can only concatenate str (not "NoneType") to str on line 579 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705942124.3260474:
    itemData(self, index: int, role: int = Qt.UserRole): too many arguments on line 599 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705942170.0439196:
    itemData(self, index: int, role: int = Qt.UserRole): too many arguments on line 599 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705942266.3774304:
    'NoneType' object has no attribute 'setStyleSheet' on line 539 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_live
1705965383.2963655:
    'song_background' on line 561 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1705965768.1525328:
    'NoneType' object has no attribute 'scaled' on line 1027 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.add_scripture_item
1706383996.3844604:
    'ccli_num' on line 19 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.__init__
1706384067.551052:
    'song_background' on line 38 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.__init__
1706398349.2558076:
    wrapped C/C++ object of type QWidget has been deleted on line 790 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1706398395.990619:
    wrapped C/C++ object of type QWidget has been deleted on line 790 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
1707340905.3804262:
    'GUI' object has no attribute 'gui' on line 1111 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1707341125.0337243:
    'GUI' object has no attribute 'gui' on line 1112 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708021659.643716:
    'int' object is not subscriptable on line 1219 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708021733.737668:
    list index out of range on line 1222 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708021809.0605924:
    list index out of range on line 1222 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708021832.6449077:
    can only concatenate list (not "str") to list on line 1222 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708021878.1819103:
    can only concatenate list (not "str") to list on line 1222 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708022845.2431877:
    list index out of range on line 1192 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708023867.0371778:
    list index out of range on line 1192 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708023900.0816956:
    list index out of range on line 1192 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1708120144.2338684:
    name 'app' is not defined on line 162 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\web_remote.py in RemoteServer.run
1708120167.130634:
    name 'app' is not defined on line 162 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\web_remote.py in RemoteServer.run
1708120220.7997575:
    name 'app' is not defined on line 162 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\web_remote.py in RemoteServer.run
1708120248.9358869:
    name 'app' is not defined on line 162 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\web_remote.py in RemoteServer.run
1708120271.1854546:
    name 'app' is not defined on line 162 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\web_remote.py in RemoteServer.run
unknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error1709931002.1628017:
    'LyricDisplayWidget' object has no attribute 'lyric_label' on line 1146 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
unknown server error1709931738.6931777:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709931784.7039647:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709931852.6179268:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709931890.8922052:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709931921.456811:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709931953.2374034:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932089.9560554:
    'NoneType' object has no attribute 'height' on line 1156 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932127.2454474:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932151.6626751:
    'NoneType' object has no attribute 'height' on line 1156 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932187.2069225:
    'NoneType' object has no attribute 'height' on line 1157 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932212.2519665:
    'NoneType' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932272.2355537:
    'QPainterPath' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932362.6426253:
    'QPainterPath' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1709932381.4021022:
    'QPainterPath' object has no attribute 'height' on line 1155 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1710119798.2483158:
    list index out of range on line 1191 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.parse_scripture_by_verse
1710123965.2424252:
    'NoneType' object has no attribute 'data' on line 894 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710124029.0617187:
    'NoneType' object has no attribute 'data' on line 894 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710124067.684159:
    'NoneType' object has no attribute 'data' on line 895 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710124087.89374:
    'NoneType' object has no attribute 'data' on line 895 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710124292.48423:
    'NoneType' object has no attribute 'data' on line 897 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710124316.039835:
    'NoneType' object has no attribute 'text' on line 922 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710124539.1807752:
    arguments did not match any overloaded call:
  insertItem(self, row: int, item: Optional[QListWidgetItem]): argument 1 has unexpected type 'NoneType'
  insertItem(self, row: int, label: Optional[str]): argument 1 has unexpected type 'NoneType' on line 919 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
unknown server error1710199114.2566247:
    arguments did not match any overloaded call:
  boundingRect(self, text: Optional[str], textOption: QTextOption): argument 1 has unexpected type 'list'
  boundingRect(self, text: Optional[str]): argument 1 has unexpected type 'list'
  boundingRect(self, rect: QRect, flags: int, text: Optional[str], tabStops: int = 0, tabArray: Optional[List[int]] = None): argument 1 has unexpected type 'list'
  boundingRect(self, x: int, y: int, width: int, height: int, flags: int, text: Optional[str], tabStops: int = 0, tabArray: Optional[List[int]] = None): argument 1 has unexpected type 'list' on line 1538 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in LyricDisplayWidget.paint_text
1710199141.110938:
    string index out of range on line 1538 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in LyricDisplayWidget.paint_text
1710203452.9729805:
    cannot access local variable 'text' where it is not associated with a value on line 1341 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in LyricDisplayWidget.paint_text
1710267155.699469:
    arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float' on line 1432 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in LyricDisplayWidget.paint_text
unknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error1710371886.3892:
    arguments did not match any overloaded call:
  QColor(color: Qt.GlobalColor): argument 1 has unexpected type 'str'
  QColor(rgb: int): argument 1 has unexpected type 'str'
  QColor(rgba64: QRgba64): argument 1 has unexpected type 'str'
  QColor(variant: Any): too many arguments
  QColor(): too many arguments
  QColor(r: int, g: int, b: int, alpha: int = 255): argument 1 has unexpected type 'str'
  QColor(name: str): too many arguments
  QColor(a0: QColor): argument 1 has unexpected type 'str' on line 268 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710371891.771794:
    arguments did not match any overloaded call:
  QColor(color: Qt.GlobalColor): argument 1 has unexpected type 'str'
  QColor(rgb: int): argument 1 has unexpected type 'str'
  QColor(rgba64: QRgba64): argument 1 has unexpected type 'str'
  QColor(variant: Any): too many arguments
  QColor(): too many arguments
  QColor(r: int, g: int, b: int, alpha: int = 255): argument 1 has unexpected type 'str'
  QColor(name: str): too many arguments
  QColor(a0: QColor): argument 1 has unexpected type 'str' on line 268 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710371893.3146172:
    'NoneType' object has no attribute 'scaled' on line 1085 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.add_scripture_item
1710371920.2805378:
    invalid literal for int() with base 10: 'black' on line 269 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710371923.6964157:
    invalid literal for int() with base 10: 'black' on line 269 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710371925.1762364:
    'NoneType' object has no attribute 'scaled' on line 1086 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.add_scripture_item
unknown server error1710384602.2440696:
    'GUI' object has no attribute 'use_shadow' on line 278 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710384606.5356472:
    'GUI' object has no attribute 'use_shadow' on line 278 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710384608.0591254:
    'NoneType' object has no attribute 'scaled' on line 1094 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.add_scripture_item
unknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error1710450228.9008472:
    'NoneType' object has no attribute 'data' on line 907 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710450244.5344608:
    'NoneType' object has no attribute 'data' on line 907 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710450323.4781232:
    'NoneType' object has no attribute 'data' on line 907 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710450355.9149885:
    'NoneType' object has no attribute 'data' on line 907 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710450409.6735523:
    'NoneType' object has no attribute 'data' on line 907 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\media_widget.py in MediaWidget.add_song_to_service
1710457222.2296274:
    'self' on line 777 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.error_log
1710457358.5956707:
    'GUI' object has no attribute 'use_shadow' on line 285 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710457361.7758853:
    'NoneType' object has no attribute 'scaled' on line 1059 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.add_scripture_item
1710457362.4848182:
    'GUI' object has no attribute 'use_shadow' on line 285 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710457369.365781:
    'song_background' on line 51 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.__init__
1710457383.6793592:
    can only concatenate str (not "NoneType") to str on line 374 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1710541691.2459497:
    'ProjectOn' object has no attribute 'image_list' on line 706 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.load_service
unknown server errorunknown server errorunknown server error1713390663.5002809:
    'NoneType' object has no attribute 'data' on line 628 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_preview
unknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error1713553918.9862564:
    cannot access local variable 'table' where it is not associated with a value on line 492 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.delete_item
1713553922.513416:
    cannot access local variable 'table' where it is not associated with a value on line 492 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.delete_item
1713554112.4213235:
    [WinError 2] The system cannot find the file specified: 'C:\\Users\\pasto\\Nextcloud\\Documents\\Python Workspace\\project_on/data/videos/Video MP4_Lake - testfile.mp4' on line 483 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.delete_item
1713554121.0878649:
    [WinError 2] The system cannot find the file specified: 'C:\\Users\\pasto\\Nextcloud\\Documents\\Python Workspace\\project_on/data/videos/Video MP4_Lake - testfile.mp4' on line 483 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.delete_item
unknown server errorunknown server errorunknown server error1713554510.9125838:
    [WinError 2] The system cannot find the file specified: 'C:\\Users\\pasto\\Nextcloud\\Documents\\Python Workspace\\project_on/data/videos/Video MP4_Lake - testfile.mp4' on line 483 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.delete_item
1713554749.1445634:
    cannot access local variable 'table' where it is not associated with a value on line 495 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.delete_item
unknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error1714509188.9451182:
    'in <string>' requires string as left operand, not NoneType on line 533 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1714509296.1121643:
    'in <string>' requires string as left operand, not NoneType on line 533 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
unknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error
1715097541.4164364:
    'GUI' object has no attribute 'gui' on line 682 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098082.7402565:
    'GUI' object has no attribute 'gui' on line 682 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098105.6853573:
    'GUI' object has no attribute 'settings' on line 684 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098181.796269:
    'global_font' on line 684 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098300.7153544:
    'global_font' on line 684 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098352.9935062:
    'Toolbar' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098425.8597558:
    'FontWidget' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098454.8957393:
    'FontWidget' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098480.1773324:
    'FontWidget' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098501.5913525:
    'FontWidget' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098662.486738:
    'FontWidget' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098699.6729674:
    'FontWidget' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715098755.233859:
    'FontWidget' object has no attribute 'font_list_widget' on line 688 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715115103.4516263:
    can only concatenate str (not "NoneType") to str on line 541 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715115166.2765203:
    can only concatenate str (not "NoneType") to str on line 541 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settingsunknown server errorunknown server errorunknown server errorunknown server error
1715210284.0083852:
    'Toolbar' object has no attribute 'song_background_combobox' on line 606 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715210332.496967:
    'Toolbar' object has no attribute 'song_background_combobox' on line 606 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715210519.3354664:
    'Toolbar' object has no attribute 'song_background_combobox' on line 609 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715210525.2049735:
    'GUI' object has no attribute 'logo_label' on line 848 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.set_logo_image
1715210599.4698033:
    'NoneType' object has no attribute 'blockSignals' on line 609 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715210605.0095134:
    'GUI' object has no attribute 'logo_label' on line 848 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.set_logo_image
1715211209.2947981:
    'NoneType' object has no attribute 'blockSignals' on line 609 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211215.0555403:
    'GUI' object has no attribute 'logo_label' on line 848 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.set_logo_image
1715211256.1545572:
    'NoneType' object has no attribute 'blockSignals' on line 609 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211381.0258422:
    'NoneType' object has no attribute 'blockSignals' on line 609 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211406.9025085:
    'GUI' object has no attribute 'logo_label' on line 848 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.set_logo_image
1715211544.218918:
    'NoneType' object has no attribute 'blockSignals' on line 609 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211602.899057:
    'NoneType' object has no attribute 'blockSignals' on line 610 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211646.519442:
    'NoneType' object has no attribute 'blockSignals' on line 610 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211758.1562428:
    'NoneType' object has no attribute 'blockSignals' on line 610 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211883.4039695:
    'NoneType' object has no attribute 'blockSignals' on line 612 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211924.7450235:
    'NoneType' object has no attribute 'blockSignals' on line 612 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715211988.6769419:
    'NoneType' object has no attribute 'blockSignals' on line 610 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715212006.3882482:
    'NoneType' object has no attribute 'blockSignals' on line 610 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715212024.5855243:
    'NoneType' object has no attribute 'blockSignals' on line 610 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715212038.7749255:
    'NoneType' object has no attribute 'blockSignals' on line 610 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715212188.549523:
    'SettingsWidget' object has no attribute 'font_face_list' on line 34 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.__init__
1715212290.1056635:
    wrapped C/C++ object of type FontWidget has been deleted on line 796 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in FontWidget.blockSignals
1715212374.020037:
    'SettingsWidget' object has no attribute 'stage_font_spinbox' on line 37 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.__init__
1715212468.3895812:
    'SettingsWidget' object has no attribute 'stage_font_spinbox' on line 37 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.__init__unknown server error
1715223735.447617:
    invalid literal for int() with base 10: 'rgb(255' on line 558 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
1715265760.5251021:
    'NoneType' object has no attribute 'append' on line 177 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715265764.3132977:
    'NoneType' object has no attribute 'append' on line 177 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715265820.2718434:
    arguments did not match any overloaded call:
  addItem(self, text: Optional[str], userData: Any = None): argument 1 has unexpected type 'QListWidgetItem'
  addItem(self, icon: QIcon, text: Optional[str], userData: Any = None): argument 1 has unexpected type 'QListWidgetItem' on line 181 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266127.8950894:
    'NoneType' object has no attribute 'append' on line 180 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266130.6513157:
    'NoneType' object has no attribute 'append' on line 180 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266155.078341:
    arguments did not match any overloaded call:
  addAction(self, icon: QIcon, text: Optional[str]): argument 1 has unexpected type 'list'
  addAction(self, icon: QIcon, text: Optional[str], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, icon: QIcon, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int]): argument 1 has unexpected type 'list'
  addAction(self, icon: QIcon, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str]): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int]): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, action: Optional[QAction]): argument 1 has unexpected type 'list' on line 183 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266176.6573954:
    arguments did not match any overloaded call:
  addAction(self, icon: QIcon, text: Optional[str]): argument 1 has unexpected type 'list'
  addAction(self, icon: QIcon, text: Optional[str], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, icon: QIcon, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int]): argument 1 has unexpected type 'list'
  addAction(self, icon: QIcon, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str]): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int]): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, text: Optional[str], shortcut: Union[QKeySequence, QKeySequence.StandardKey, Optional[str], int], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'list'
  addAction(self, action: Optional[QAction]): argument 1 has unexpected type 'list' on line 183 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266451.6949275:
    'ProjectOn' object has no attribute 'image_items' on line 164 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266454.435154:
    'ProjectOn' object has no attribute 'image_items' on line 164 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266473.7485545:
    arguments did not match any overloaded call:
  addItem(self, text: Optional[str], userData: Any = None): argument 1 has unexpected type 'QIcon'
  addItem(self, icon: QIcon, text: Optional[str], userData: Any = None): argument 2 has unexpected type 'list' on line 180 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266502.919598:
    arguments did not match any overloaded call:
  addItem(self, text: Optional[str], userData: Any = None): argument 1 has unexpected type 'QIcon'
  addItem(self, icon: QIcon, text: Optional[str], userData: Any = None): argument 2 has unexpected type 'list' on line 180 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refresh
1715266571.8632169:
    'NoneType' object has no attribute 'close' on line 185 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in ImageCombobox.refreshunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error
Wed May 15 14:25:09 2024:
    'NoneType' object has no attribute 'isPlaying' on line 1151 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.change_display
Wed May 15 14:25:42 2024:
    'NoneType' object has no attribute 'isPlaying' on line 1151 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.change_display
Wed May 15 14:42:52 2024:
    'NoneType' object has no attribute 'deleteLater' on line 1147 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.change_displayunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error
Wed May 15 15:22:12 2024:
    wrapped C/C++ object of type QVideoSink has been deleted on line 633 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Wed May 15 15:22:17 2024:
    cannot access local variable 'pixmap' where it is not associated with a value on line 642 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Wed May 15 18:22:54 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 18:24:11 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 18:32:18 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 18:58:29 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_themeunknown server error
Wed May 15 18:59:32 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_themeunknown server error
Wed May 15 19:00:18 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_themeunknown server error
Wed May 15 19:01:34 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_themeunknown server error
Wed May 15 19:02:05 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_themeunknown server error
Wed May 15 19:06:51 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 19:07:22 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 19:07:50 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:51:02 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:51:56 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:52:37 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:53:22 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:54:37 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:55:36 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:56:55 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 20:57:52 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 436 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_themeunknown server error
Wed May 15 21:00:59 2024:
    setStyleSheet(self, styleSheet: Optional[str]): not enough arguments on line 443 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 21:04:20 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 397 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 21:05:00 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 397 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 21:06:11 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 397 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 21:10:09 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 397 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 21:12:33 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 417 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_theme
Wed May 15 21:18:53 2024:
    'NoneType' object has no attribute 'set_style_sheet' on line 421 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_themeunknown server errorunknown server errorunknown server errorunknown server error
Thu May 16 09:17:23 2024:
    'FontFaceComboBox' object has no attribute 'apply_settings' on line 427 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.apply_settingsunknown server errorunknown server error
Thu May 16 11:21:51 2024:
    'int' object has no attribute 'replace' on line 366 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_song
Thu May 16 11:23:39 2024:
    'int' object has no attribute 'replace' on line 366 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_song
Thu May 16 11:24:09 2024:
    'int' object has no attribute 'replace' on line 366 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_songunknown server errorunknown server errorunknown server error
Thu May 16 12:36:14 2024:
    near ",": syntax error on line 403 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_songunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error
Thu May 16 14:46:03 2024:
    'NoneType' object is not subscriptable on line 1096 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_live
Thu May 16 14:48:24 2024:
    'NoneType' object is not subscriptable on line 1115 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_liveunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error
Thu May 16 16:36:58 2024:
    invalid literal for int() with base 10: 'rgb(0' on line 702 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Thu May 16 16:37:42 2024:
    invalid literal for int() with base 10: 'rgb(0' on line 702 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Thu May 16 16:40:17 2024:
    invalid literal for int() with base 10: 'rgb(0' on line 702 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Thu May 16 16:40:33 2024:
    invalid literal for int() with base 10: 'rgb(0' on line 702 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settingsunknown server error
Thu May 16 16:54:43 2024:
    can only concatenate str (not "int") to str on line 452 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_custom
Thu May 16 16:56:13 2024:
    can only concatenate str (not "bool") to str on line 452 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_custom
Thu May 16 16:57:30 2024:
    can only concatenate str (not "bool") to str on line 452 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_custom
Thu May 16 16:58:26 2024:
    can only concatenate str (not "bool") to str on line 452 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_custom
Thu May 16 16:59:12 2024:
    'list' object cannot be interpreted as an integer on line 450 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_custom
Thu May 16 16:59:45 2024:
    can only concatenate str (not "bool") to str on line 454 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_custom
Thu May 16 17:01:37 2024:
    'NoneType' object is not subscriptable on line 1098 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_live
Fri May 17 10:17:59 2024:
    'NoneType' object has no attribute 'blockSignals' on line 894 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in FontWidget.blockSignals
Fri May 17 10:18:36 2024:
    'NoneType' object has no attribute 'blockSignals' on line 894 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in FontWidget.blockSignalsunknown server error
Fri May 17 10:19:13 2024:
    find(a0: PyQt5.sip.voidptr): argument 1 has unexpected type 'str' on line 916 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py in FontWidget.apply_settingsunknown server errorunknown server errorunknown server error
Fri May 17 12:57:54 2024:
    'NoneType' object is not subscriptable on line 1098 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_live
Fri May 17 12:58:51 2024:
    'NoneType' object is not subscriptable on line 1098 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_live
Fri May 17 13:01:09 2024:
    'NoneType' object is not subscriptable on line 1117 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_live
Fri May 17 13:02:04 2024:
    'NoneType' object is not subscriptable on line 1123 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_live
Fri May 17 13:02:42 2024:
    'NoneType' object is not subscriptable on line 1098 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.send_to_liveunknown server error
Sat May 18 14:46:42 2024:
    UNHANDLED EXCEPTION
    'AttributeError'
    'QWidget' object has no attribute 'mouse_release_signal'
    file C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\widgets.py, line 265 in eventFilter
Sat May 18 14:46:48 2024:
    UNHANDLED EXCEPTION
    'TypeError'
    invalid result from CustomSlider.mouseReleaseEvent()
    unknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server errorunknown server error
Wed May 29 10:58:04 2024:
    list index out of range on line 402 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_song
Wed May 29 11:01:48 2024:
    list index out of range on line 402 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_song
Wed May 29 11:05:08 2024:
    17 values for 18 columns on line 405 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\main.py in ProjectOn.save_song
Mon Jun  3 22:44:13 2024:
    'shadow_offset' on line 819 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Mon Jun  3 22:44:49 2024:
    'shadow_offset' on line 819 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Mon Jun  3 22:46:51 2024:
    'shadow_offset' on line 819 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Mon Jun  3 22:47:06 2024:
    'shadow_offset' on line 819 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Mon Jun  3 22:48:01 2024:
    'shadow_offset' on line 821 of C:\Users\pasto\Nextcloud\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Wed Jun  5 22:12:31 2024:
    UNHANDLED EXCEPTION
    'AttributeError'
    'NoneType' object has no attribute 'objectName'
    file X:\Documents\Python Workspace\project_on\edit_widget.py, line 953 in save_customunknown server errorunknown server errorunknown server errorunknown server errorunknown server error
Fri Jul 19 16:25:18 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 65 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceComboBox.populate_widget
Fri Jul 19 16:25:28 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:27:58 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:29:50 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:32:16 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:33:23 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:33 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:34 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:35 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:36 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:37 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:38 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:33:39 2024:
    'NoneType' object has no attribute 'videoFrame' on line 782 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.grab_display
Fri Jul 19 16:41:18 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:42:56 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:47:13 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Fri Jul 19 16:48:27 2024:
    families(self, writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): first argument of unbound method must have type 'QFontDatabase' on line 31 of \\LBCN\jeremy\Documents\Python Workspace\project_on\widgets.py in FontFaceListWidget.populate_widget
Sat Jul 20 10:48:58 2024:
    'GUI' object has no attribute 'apply_theme' on line 696 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.apply_settings
Wed Jul 24 11:16:17 2024:
    'NoneType' object has no attribute 'data' on line 1163 of \\LBCN\jeremy\Documents\Python Workspace\project_on\gui.py in GUI.send_to_liveunknown server errorunknown server error
Thu Jul 25 15:12:38 2024:
    'SettingsWidget' object has no attribute 'font_settings_widget' on line 493 of \\LBCN\jeremy\Documents\Python Workspace\project_on\settings_widget.py in SettingsWidget.apply_settings
Thu Jul 25 15:58:09 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1324 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__
Thu Jul 25 16:00:52 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1324 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__
Thu Jul 25 16:04:01 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1324 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__
Thu Jul 25 16:19:03 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1326 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__
Thu Jul 25 16:20:15 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1326 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__
Thu Jul 25 16:23:54 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1325 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__
Thu Jul 25 16:26:02 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1325 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__
Thu Jul 25 16:28:02 2024:
    UNHANDLED EXCEPTION
    'ZeroDivisionError'
    division by zero
    file X:\Documents\Python Workspace\project_on\main.py, line 1325 in <module, file X:\Documents\Python Workspace\project_on\main.py, line 103 in __init__, file X:\Documents\Python Workspace\project_on\gui.py, line 95 in __init__